@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.bilicraft.mantle_fabric.registration;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
